### ISSUE TITLE
Getting an error trying to make shapes

### ISSUE THREAD

**Issue by Setarii** [Datacup/dfhackscripts#18]
Finally decided to try and tackle using this tool today, but it's just straight throwing errors for everything. Here is the error, it's the same no matter what I attempt to do with it.

`E: FloatDomainError: NaN
 hack/scripts/digshape.rb:335:in `round'
 hack/scripts/digshape.rb:335:in `block in drawPolygon'
 hack/scripts/digshape.rb:334:in `each'
 hack/scripts/digshape.rb:334:in `drawPolygon'
 hack/scripts/digshape.rb:527:in `<top (required)>'
 eval:2:in `load'
 eval:2:in `block in <main>'
 eval:2:in `catch'`

**Comment by ivantumanov** [comment]
Confirmed that cursor remaining on origin might be what's causing this problem

**Comment by Setarii** [comment]
Yes, this was the issue.
